// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3j3-JAktwoD4AN1beh2aVIwae4_Kt55M',
    appId: '1:1026374128989:web:d1bdcdbe4ed60a443604b4',
    messagingSenderId: '1026374128989',
    projectId: 'food-app-17dc5',
    authDomain: 'food-app-17dc5.firebaseapp.com',
    storageBucket: 'food-app-17dc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaHtN5UqB7cuEzCghdjol1Rr6ctTaKYnc',
    appId: '1:1026374128989:android:3f4c38035029fdf23604b4',
    messagingSenderId: '1026374128989',
    projectId: 'food-app-17dc5',
    storageBucket: 'food-app-17dc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcY7kfMPH39xf2V_px3okaRmIqIHGOVKc',
    appId: '1:1026374128989:ios:13784b0de56ab3253604b4',
    messagingSenderId: '1026374128989',
    projectId: 'food-app-17dc5',
    storageBucket: 'food-app-17dc5.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcY7kfMPH39xf2V_px3okaRmIqIHGOVKc',
    appId: '1:1026374128989:ios:13784b0de56ab3253604b4',
    messagingSenderId: '1026374128989',
    projectId: 'food-app-17dc5',
    storageBucket: 'food-app-17dc5.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3j3-JAktwoD4AN1beh2aVIwae4_Kt55M',
    appId: '1:1026374128989:web:f68ab5b02b42701b3604b4',
    messagingSenderId: '1026374128989',
    projectId: 'food-app-17dc5',
    authDomain: 'food-app-17dc5.firebaseapp.com',
    storageBucket: 'food-app-17dc5.firebasestorage.app',
  );
}
